#!/usr/bin/env python3
"""
generate_header.py (塔菲逆核 fork 版)

生成 key_generated.h —— 供 app/src/main/cpp/signature_verify.cpp 使用的
XOR 编码数组 + 轮转多字节 XOR 密钥。

原始文件来自上游 SOMCP (app/generate_header.py, AGPL-3.0-or-later,
Copyright (C) 2026 bilieebiliee1-design)，本 fork 仅做两处适配：

  1. 上游从 $TM 环境变量读取构建期密钥（CI secret），缺失即 FATAL。
     塔菲逆核的 CI 无该 secret（且本仓库的 pin 值本身不是机密：
     签名摘要已以 XOR 形式存在于 Kotlin IntegrityGuard 中），
     因此内置一个固定的默认密钥，未提供 --key / $TM 时直接使用。
  2. 编码的明文改为本 fork 的 pin 值：
       - 发布签名证书 SHA-256 = IntegrityGuard.expectedSignerDigest()
       - applicationId          = com.taffynihe
     上游值（90FEDAC1... / com.soreverse.mcp）不再适用。

用法:
    python generate_header.py --dst app/src/main/cpp/key_generated.h
    python generate_header.py --key 0123456789abcdef --dst /tmp/key_generated.h
"""
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 bilieebiliee1-design
# 塔菲逆核 fork adaptations: hUh63/TaffyNiHe

import argparse
import os
import sys

# ── 本 fork 默认密钥（8 字节；未提供 --key/$TM 时使用）──
DEFAULT_KEY_HEX = "4b7e21c5930de83a"

# ── 本 fork 的 pin 值 ──
# 发布签名证书 SHA-256（与 Kotlin IntegrityGuard.OBFUSCATED_SIGNER_DIGEST 解码结果一致）
EXPECTED_SHA256 = "3CC2D37005933116AC2C91735BC9C72A48C2319AF58EA224AD84EF850F7E1ABB"
# applicationId（注意：不是 namespace；namespace 保持 com.soreverse.mcp 以便 JNI 名）
EXPECTED_PACKAGE = "com.taffynihe"


def parse_key(hex_str: str) -> list:
    """Parse a 16-char hex string into 8 bytes."""
    s = hex_str.replace(" ", "").replace("0x", "").lower()
    if len(s) != 16:
        raise ValueError(f"Key must be 16 hex chars (got {len(s)}): {hex_str}")
    return [int(s[i:i + 2], 16) for i in range(0, 16, 2)]


def xor_encode(plain: str, key: list) -> list:
    """Encode plaintext bytes using rotating XOR with the given key."""
    return [ord(c) ^ key[i % len(key)] for i, c in enumerate(plain)]


def fmt_array(name: str, data: list, indent: int = 4) -> str:
    """Format a byte array as C source code."""
    spaces = " " * indent
    lines = [f"{spaces}static const uint8_t {name}[] = {{\n"]
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        lines.append(f"{spaces}    {', '.join(f'0x{b:02X}' for b in chunk)},\n")
    lines.append(f"{spaces}}};\n")
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate key_generated.h with XOR-encoded signature arrays"
    )
    parser.add_argument("--key", default=None,
                        help="16-char hex key (8 bytes). Falls back to $TM, then built-in default.")
    parser.add_argument("--dst", required=True, help="Output path for key_generated.h")
    args = parser.parse_args()

    key_hex = args.key or os.environ.get("TM", "").strip() or DEFAULT_KEY_HEX
    try:
        key = parse_key(key_hex)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    arrays = {
        # signature_verify.cpp 引用的 4 个符号
        "kEncodedExpectedSha256": xor_encode(EXPECTED_SHA256, key),
        "kEncodedExpectedPackage": xor_encode(EXPECTED_PACKAGE, key),
    }
    lengths = {
        "kEncodedExpectedSha256": len(EXPECTED_SHA256),
        "kEncodedExpectedPackage": len(EXPECTED_PACKAGE),
    }

    parts = []
    parts.append(
        "// ---------------------------------------------------------------------------\n"
        "// AUTO-GENERATED by app/generate_header.py —— DO NOT EDIT\n"
        "// 塔菲逆核 fork: pin = 发布签名证书 SHA-256 + applicationId(com.taffynihe)\n"
        "// ---------------------------------------------------------------------------\n"
        "#pragma once\n\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "// 轮转多字节 XOR 密钥\n"
        "static const uint8_t kXorKey[] = {"
        + ", ".join(f"0x{b:02X}" for b in key)
        + "};\n"
        "static const size_t kXorKeyLen = " + str(len(key)) + ";\n\n"
    )
    for name in ("kEncodedExpectedSha256", "kEncodedExpectedPackage"):
        parts.append(fmt_array(name, arrays[name]))
        parts.append(f"static const size_t {name}Len = {lengths[name]};\n\n")

    header = "".join(parts)
    os.makedirs(os.path.dirname(os.path.abspath(args.dst)), exist_ok=True)
    with open(args.dst, "w", encoding="utf-8") as f:
        f.write(header)
    print(f"[gen] wrote {args.dst} ({len(header)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
